### ISSUE TITLE
Error Handling 

### ISSUE THREAD

**Issue by ChoiEungi** [GIST-Petition-Site-Project/GIST-petition-server#1]
Goal 
- Error Handling을 통해 오류가 났을 떄 클라이언트에 적절한 에러 메세지를 출력한다.

**Comment by wannte** [comment]
이 부분도 ExceptionHandler의 도입으로 어느정도 방법은 찾았다 생각합니다.
현재 적용되지 않는 부분도 있을 수 있는데, 그 부분은 그 때 상황에 해당하는 이슈를 별도로 작성해서 진행해봅시다~
