### ISSUE TITLE
로그인 되었는지 체크하여 리턴값을 주는 api를 만든다.

### ISSUE THREAD

**Issue by koseyeon** [GIST-Petition-Site-Project/GIST-petition-server#109]
클라이언트 단에서는 현재 쿠키에 가지고 있는 세션id 가 만료되었는지 아닌지 알수 없다.
(새 탭으로 index.html을 열었을 때 로그인 여부에 따라 다른 창을 보여주어야 하는데 그럴려면 먼저 로그인이 되어있는지 아닌지 체크해야 한다.)
따라서 로그인 여부를 체크해주기 위한 api가 필요하다.

**Comment by wannte** [comment]
[세션 api참고자료](https://developer.okta.com/docs/reference/api/sessions)

**Comment by koseyeon** [comment]
user/me 가 해당 역할을 수행하기로 하였씁니다
