### ISSUE TITLE
[질문] GET /users/me 에 password 항목이 의도된건가요?

### ISSUE THREAD

**Issue by kimjngyun** [GIST-Petition-Site-Project/GIST-petition-server#118]
password 다이제스트가 돌아오는게 의도된 것인지 궁금합니다!

![image](https://user-images.githubusercontent.com/63437430/148934279-7eb62fbe-0b14-4745-be37-6d548d1f8637.png)

**Comment by koseyeon** [comment]
id, 패스워드는 보내지 않아야 할것 같습니다! 수정하겠습니다.
