### ISSUE TITLE
N+1 문제를 해결해야 한다.

### ISSUE THREAD

**Issue by ChoiEungi** [GIST-Petition-Site-Project/GIST-petition-server#159]
`List<Post>`를 불러올 때, 그와 관련된 Agreement를 모두 조회하는 문제가 발생한다.

**Comment by ChoiEungi** [comment]
N+1 문제를 해결하기 위해서는 fetch join을 이용해야 하는데 저희 서비스에서 모든 청원을 조회할 때, Pagable을 사용하기 때문에 fetch join을 사용하기 어렵습니다
<img width="661" alt="스크린샷 2022-02-08 오후 10 05 57" src="https://user-images.githubusercontent.com/70755947/152992869-40ab4d57-e324-4718-be7b-7c0dc6463013.png">
!

**Comment by GuruneLee** [comment]
https://tecoble.techcourse.co.kr/post/2021-07-26-jpa-pageable/

@BatchSize 어노테이션을 활용하는 방법이 소개되어있네요. 참고해서 고쳐보면 좋을듯 합니다.
