### ISSUE TITLE
전체 조회페이지에서는 내부 값들을 모두 보내줄지 고민한다.

### ISSUE THREAD

**Issue by ChoiEungi** [GIST-Petition-Site-Project/GIST-petition-server#161]
지금은 Post의 개수가 작아서 문제가 없지만, 이후 서비스가 커질 때 무거워져 문제가 발생할 수 있다.

**Comment by GuruneLee** [comment]
청원보기 페이지에서 보여줄 미리보기 정보랑
글을 클릭했을 때 보이는 글전체 정보랑
Dto 를 분리해볼까요?

동의하면 구독 좋아요 알람설정 해주세요
