### ISSUE TITLE
Petition과 Agreement의 연관관계에 대해서 고민해본다.

### ISSUE THREAD

**Issue by ChoiEungi** [GIST-Petition-Site-Project/GIST-petition-server#185]
현재 저희 프로젝트에서 Petition과 Agreement의 연관관계는 1:N으로 연관관계의 주인(foreign key를 갖는 Entity)은 Agreement입니다. 하지만 연관관계의 주인이 아닌 Petition에서 `applyAgreement()` 메서드와 영속성 전이(CascadeType.ALL)를 이용해 연관관계의 주인(Agreement)의 데이터를 삽입하고 있습니다. 일반적으로 연관관계의 주인에 대한 데이터는 연관관계의 주인만 데이터를 삽입, 수정할 수 있다고 합니다. 이 연관관계에 대해서 고민해보면 좋을 것 같습니다.

**Comment by wannte** [comment]
기존에는 `@OneToMany` 단방향으로 구성하고 `@OneToMany(cascade = CascadeType.ALL, orphanRemoval = true)`의 문법을 사용함으로써 Agreement를 추가할 수 있었습니다.

이 문법에 대해 아직 어색한 분들을 위해 조금 설명을 추가해 보자면,
1. cascade = CascadeType.All
우리 Petition Entity에 적용된 것을 설명해보겠습니다. Petition의 List<Agreement>에 CascadeType.All 설정을 진행하게 되면, 해당 list의 추가하게 된 Agreement Entity 또한 영속성 컨텍스트에 관리되게 됩니다. 그렇기에 지금의 구현에서는  AgreementRepository에 직접 등록하지 않고 `this.agreements.add(new Agreement(user.getId(), description, this));` 만 진행해더라도 Agreement가 데이터베이스에 저장이 될 수 있었던 겁니다!

2. orphanRemoval=true
이름 그대로, 고아가 된 객체를 삭제하는 로직입니다. 만약 Petition Entity를 삭제하게 된다면, 이를 구성하고 있던 Agreement는 모두 고아가 되고, 자동으로 삭제하게 됩니다.
---
## 이슈에 대한 생각
처음 이 부분에 대해 연관관계를 고민할 때, JPA에 대해 이해가 부족했던 우리 팀의 상황에서 가장 간단하게 이해하고 구현할 수 있던 방법을 고민했고, 그게 `OneToMany 단방향 + 위의 문법 사용` 입니다.

이 방법의 장점은, Petition이 Agreement를 가지고 있는 객체 지향적인 구조?(사람이 생각하기에 직관적인 구조)를 가지며, 이해하기 쉬운 장점이 있습니다. 연관관계의 주인을 통해 관리하지 않더라도 우리가 필요한 요구사항을 구하는데는 어려움이 없었습니다.

하지만, 이제 해당 청원에 대한 동의 내역을 보여주는 로직이 추가되었음으로, 양방향 관계가 필연적으로 되었기 때문에 수정을 진행하는 것이 옳다고 생각합니다.

지금 떠오르는 방법은 CascadeType.All은 불필요한 것으로 보이며, AgreementRepository.save()를 통해 동의를 저장하고, 편의 메소드를 정의 해주는 방식으로 풀어낼 수 있을 것 같습니다.

참고할만한 자료로 아래를 보면 좋을 거 같아요.(영한님 책을 정리한 내용이라 책을 보는 것도 좋을 것 같습니다)
[[JPA] @OneToMany, 일대다[1:N] 관계](https://ict-nroo.tistory.com/125)
