### ISSUE TITLE
[버그?] PUT: petitions/{petitionId} 에서 description만 수정됩니다.

### ISSUE THREAD

**Issue by kimjngyun** [GIST-Petition-Site-Project/GIST-petition-server#189]
<img width="552" alt="image" src="https://user-images.githubusercontent.com/63437430/153400588-e192f795-cdc6-4e68-ad86-7622b34f6ac3.png">

여기 나와있는대로 categoryId, title, description 수정 사항을 요청보냈으나 description 만 변경되는것 처럼 동작합니다. 

혹시 제목이나 카테고리 수정이 안되도록 의도한것인지 궁금하네요. 

++ description변경은 잘 되는것을 확인했습니다.

**Comment by koseyeon** [comment]
지금 해결하겠습니다
