### ISSUE TITLE
사전 동의 기능을 추가했을 때 ID로 접근하게 되면, 링크가 없는 사용자도 해당 청원을 접근할 수 있는 문제가 있음.

### ISSUE THREAD

**Issue by wannte** [GIST-Petition-Site-Project/GIST-petition-server#196]

**Comment by koseyeon** [comment]
해당 문제를 해결하기 위해 두 가지 접근 방식을 생각해보았습니다.

1. 기존 Petition 엔티티의 primary key로 Long type의 Id가 아니라 UUID type의 id를 사용하도록 한다. 
  petition을 불러오기 위한 GET 요청을 /petitions/{petitionId} 가 아니라 /petitions/{petitionUUID}로 하도록 합니다.
  이 경우 모든 청원 불러오기 시 노출이 되면 안되는 청원을 걸러서 가져와야하므로 쿼리의 복잡성이 올라갑니다.

2. tempPetition을 아예 따로 만든다.
   이 경우, 사용자에게 보여질 청원과 보여지지 않을 청원의 도메인이 완전히 분리되므로,
  사용자에게 보여줄 청원 목록을 가져오는 쿼리의 복잡성이 줄어들고(where exposed=True 같은 문이 안 들어감),
  코드를 짤 때도 실수로 노출시킬 위험이 줄어든다고 생각합니다.
  그러나, tempPetition이었던 청원을 Petiton으로 옮기는 과정에서 비용이 많이 들것 같다고 생각이 듭니다.(연관되어있는 동의들도 같이 옮겨야 하므로)

**Comment by koseyeon** [comment]
만약 Petition의 id로 UUID를 사용하게 된다면,
주의해야할 점으로 데이터베이스에 BINARY(16) 으로 저장되도록 명시해주어야 한다고 합니다.
그 이유는 JPA가 데이터베이스에 UUID를 저장할 때 기본적으로 255바이트 크기의 binary로 저장하기 때문에 uuid를 쓰고 남는 바이트들은 0으로 채워져서 우리가 의도한 대로 저장되지 않는다고 합니다, 
https://jehuipark.github.io/java/my-sql-binary-reference 를 참고하면 좋을 것 같습니다.
