### ISSUE TITLE
Prod서버에 Cloudwatch 대시보드를 연결하고 설정한다.

### ISSUE THREAD

**Issue by wannte** [GIST-Petition-Site-Project/GIST-petition-server#291]
현재 메모리 사용량 , Cpu 사용량 등의 정보를 Cloudwatch로 확인해야만 한다.

**Comment by wannte** [comment]
https://docs.aws.amazon.com/AmazonCloudWatch/latest/monitoring/installing-cloudwatch-agent-commandline.html

- cloudwatch agent를 설치한다.
- wizard를 통해 설정 파일을 생성한다. ~/cloudwatch/config.json 파일로 생성한다. 
- `sudo /opt/aws/amazon-cloudwatch-agent/bin/amazon-cloudwatch-agent-ctl -a fetch-config -m ec2 -s -c file:config.json` 으로 재 실행한다.

**Comment by koseyeon** [comment]
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/82452337/158220972-b3e99934-7f1b-482c-ace5-2517a6c12541.png">


우리의 prod서버 대시보드 입니다!
현재 추적하고 있는 지표들은 다음과 같습니다.
- CPU 사용량
- 메모리 사용량
- Error Log
- RDS CPU 사용량
- RDS ReadWrite Latency
- RDS ReadWrite Throughput
- RDS Network Throughput

또한, 해당 지표들이 일정 기준을 초과했을 때,
Slack으로 알림이 가도록 하였습니다.
