### ISSUE TITLE
반려된 청원이 만료된 청원에도 중복 노출됩니다.

### ISSUE THREAD

**Issue by kimjngyun** [GIST-Petition-Site-Project/GIST-petition-server#347]
만료된 청원을 요청하면 청원 기한이 지난 반려된 청원들도 함께 옵니다.

<img width="983" alt="image" src="https://user-images.githubusercontent.com/63437430/163838283-c0ed6bd0-7c9c-456c-8ba7-fed252712ade.png">

**Comment by GuruneLee** [comment]
오늘 밤에 내가 처리해보도록 하지요

**Comment by GuruneLee** [comment]
다 멈춰 아무것도 하지마 내가 할거야

**Comment by GuruneLee** [comment]
깜빡했다

**Comment by kimjngyun** [comment]
ㅋㅋ 해줘!
