### ISSUE TITLE
도메인 등록하기  + HTTPS에 대해 고민하기 + NGINX

### ISSUE THREAD

**Issue by wannte** [GIST-Petition-Site-Project/GIST-petition-server#39]

**Comment by wannte** [comment]
`gist-petition.com` 도메인 구입 완료

nginx 도입을 진행했으나, ec2에 nginx 와 spring 서버를 동시에 실행 했을 때, 동작하지 않는 문제 발생.

HTTPS에 대한 도입도 추후에 진행 예정.

**Comment by koseyeon** [comment]
https에 대해 공부하고 이것을 nginx에 적용한다. 자세한 문의사항은 태완이형에게로!
-> 태완이형이 https 적용 완료@
