### ISSUE TITLE
Spring Security의 의존성을 제거한다.

### ISSUE THREAD

**Issue by wannte** [GIST-Petition-Site-Project/GIST-petition-server#74]
Security를 우선 걷어내보자

**Comment by GuruneLee** [comment]
> Security를 우선 걷어내보자

Spring Security 의 BCryptPasswordEncoder 클래스를 사용하지 않고, 직접 password encryption 구현하기

**Comment by wannte** [comment]
[회원 인증 관련 회의 자료](https://docs.google.com/presentation/d/1Dy0yDVwWxCyqSr2is-GEbMmsSOsKM5cvukO_GkyEuoY/edit?usp=sharing)


## 회원 가입 정책에 관하여
1. UserRole을 입력받는다.
Manager계정의 요청이 들어왔을 때, 이를 검증할 방법이 없음
2. UserRole을 User로 통일한다.
User로 만든 후에, Manager 계정으로의 승급은 Admin계정이 진행한다. Admin 계정은 DB에 직접 입력한다.

**Comment by wannte** [comment]
### 이메일 인증의 방식을 구현하는 부분에서 까다로운 부분
이메일을 통해 인증 링크를 보내는 방식 -> 서버 사이드 렌더링에서는 보여지는 부분까지 다 컨트롤할 수 있지만, 프론트와 백엔드가 분리되어 있는 우리 서비스 같은 경우에는 이 부분이 쉽지 않음.
(View에 보여지는 것을 우리 서버가 컨트롤하지 못하기 때문)

해결 방법의 제안
1. 로그인 인증번호를 이용한다. -> 이메일에 인증번호를 보내주고, 사용자가 해당 인증 번호를 입력하여 인증을 진행하는 방식
인증 번호가 올바른 경우에만 회원가입일 가능하다.
2.
