### ISSUE TITLE
CustomException 계층화하기

### ISSUE THREAD

**Issue by wannte** [GIST-Petition-Site-Project/GIST-petition-server#75]

**Comment by wannte** [comment]
이 부분을 구현하면서, 에러메시지의 형태도 통일했으면 합니다. 앞서 용어 통일을 진행했으면 합니다.

post -> 청원
comment -> 댓글
answer -> 답변

요정도로 제안을 해봅니다

**Comment by wannte** [comment]
우선 하나의 도메인만을 수정하고 공유하는 시간을 가졌으면 좋겠습니다.

**Comment by wannte** [comment]
잘못된 요청 -> 400
인증 안됨 -> 401
인가 안됨 -> 403
서버가 안됨 -> 500

**Comment by GuruneLee** [comment]
CustomException 을 ApplicationException 의 하위로 두는 것
CustomExcpetion 의 이름을 3rdParty? Context? 

https error 코드 정하기
