### ISSUE TITLE
세션 기반 통신 기능을 구현한다.

### ISSUE THREAD

**Issue by wannte** [GIST-Petition-Site-Project/GIST-petition-server#79]

**Comment by wannte** [comment]
로그인이 안된 사용자 (인증) -> 401 (ex: 로그인이 필요합니다.)
권한이 없는 사용자 (인가) -> 403 (ex: 답변을 하기 위해서는 매니저 권한이 필요합니다)

**Comment by wannte** [comment]
Anonymous 유저 생성하기. -> Security는 왜 Anonymous를 사용하는가?

**Comment by GuruneLee** [comment]
> 로그인이 안된 사용자 (인증) -> 401 (ex: 로그인이 필요합니다.)
> 권한이 없는 사용자 (인가) -> 403 (ex: 답변을 하기 위해서는 매니저 권한이 필요합니다)

이부분은 customException 을 계층화 하면서 구현하는것이 좋아보입니다. 
일단은 응답코드와 그에따른 redirection 등을 제외한체 exception 을 던지는 것으로만 구현하고, 이게 끝나고 바로 customException 계층화를 하는것이 좋아보여용

**Comment by koseyeon** [comment]
현재 저희의 구현은 세션 저장소에 SessionUser(userId, userRole, enabled)로 하여 세션유저 객체를 저장하도록 구현하였습니다.
그런데 만약 세션유저가 세션 저장소에 저장된 이후에, 
이메일인증 여부 변경, 유저 권한 변경 등의 이유로 세션유저 객체의 정보가 수정됐을 때 어떻게 할 것인지에 대한 논의가 필요할 것 같습니다.

저희가 생각한 해결방법은 이메일인증 여부 변경, 유저 권한 변경 등은 굉장히 크리티컬한 부분이므로 세션이 유지되는 것보다 
일단 로그아웃 시키고 다시 로그인 시켜서 세션을 다시 생성하도록 하는 방향이 어떨까  싶습니다.

**Comment by koseyeon** [comment]
세션 logout 요청의 경우,  요청을 POST로 보내도록 하였고, 리턴되는 http status 코드는 204(No Content)로 리턴되도록 하였습니다.
참고 : https://stackoverflow.com/questions/3521290/logout-get-or-post

**Comment by koseyeon** [comment]
현재 구조에서는 검증을 
1. 컨트롤러에서 userRole에 대한 검증,
2. 서비스에서 작성자본인인지에 대한 검증
이렇게 두가지의 검증을 컨트롤러와 서비스 , 총 2군데에서 진행하고 있는데,
만약에 세션유저를 컨트롤러에서 서비스로 넘겨준다면 모든 검증로직을 서비스 한 군데에서 처리할수도 있을 것으로 보입니다.
(SessionUser 객체를 서비스에 넘겨주고, 서비스에서 SessionUser을 가지고 userRole을 뽑아서 쓰도록 하는 것입니다.)

그렇지만 일단은 지금의 구조가 공통검증로직과 별도검증로직을 분리할 수 있는 구조이기에 후에 AOP, 필터, 인터셉터 도입에도 용이할 것으로 보여 현재의 구조를 유지하고 앞으로 지속적으로 논의해보면 좋을 것 같습니다.

**Comment by koseyeon** [comment]
권한에 대한 검증 부분 구현을 
어떻게(필터를 통한 검증, 인터셉터를 통한 검증) 할 것 인지,
어디에서(컨트롤러 단 검증,서비스단 검증) 할 것인지,
공통적인 검증로직과 요청마다의 별도 로직의 대한 분리를 어떻게 할 것인지 등
앞으로도 지속적으로 논의해보면 좋을 것 같습니다.

또한 청원,댓글,답변에 CRUD하기 위해서 이메일인증을 완료했는지에 대한 검증을 할 때,
현재는 user에 enabled 필드를 두어서 이 enabled 가 True인지 아닌지를 검증하고 있는데, 
enabled 필드 대신 userRole을 anonymous로 두어 userRole에 대한 검증만으로 이메일 인증 여부, 권한 소유 여부 등을 검증하면 어떨지 논의해보면 좋을 것 같습니다.
