### ISSUE TITLE
AOP를 학습하고 우리 프로젝트에 적합한지 고민한다.

### ISSUE THREAD

**Issue by wannte** [GIST-Petition-Site-Project/GIST-petition-server#94]
#78 이슈의 1단계로 이슈를 나눠서 진행했으면 합니다.

간단한 워크숍을 진행하면 very good!

**Comment by wannte** [comment]
Interceptor에 대해서도 같이 고민을 해도 좋을 것 같다.

**Comment by koseyeon** [comment]
세션 도입이 다 끝난 다음에 진행하면 좋을 것 같다고 줌에서 이야기 나누었습니다!
