### ISSUE TITLE
User CRUD 요청과 권한체크 로직을 구현한다

### ISSUE THREAD

**Issue by GuruneLee** [GIST-Petition-Site-Project/GIST-petition-server#98]

**Comment by GuruneLee** [comment]
udate user 없음
delte user 권한체크 안함

**Comment by wannte** [comment]
<del>왜 말을 못해 창하<del>

해당 기능들은 admin에 한정해서 주는 게 좋을 것 같네요!

**Comment by wannte** [comment]
```java
    @GetMapping("/users")
    public ResponseEntity<List<User>> retrieveAllUsers() {
        return ResponseEntity.ok().body(userService.findAllUsers());
    }

    @GetMapping("/users/{userId}")
    public ResponseEntity<User> retrieveUser(@PathVariable Long userId) {
        return ResponseEntity.ok().body(userService.findUserById(userId));
    }
```

유저에 대한 검색을 진행하게 되면, 암호화된 패스워드까지 모두 조회되는 구조입니다. (우선 이 부분은 인지하되, 이번 PR에서는 반영하지 않겠습니다)
또한, 모두에게 유저에 대한 정보를 오픈할 수는 없습니다. (-> 이 또한, Admin의 권한으로 두어야 한다고 생각합니다. 비대위라고해서, 학생들의 목록을 모아서 볼 수 있으면 안된다고 생각합니다.) 이번 PR에서는 어드민 권한만이 조회를 할 수 있도록 권한을 두겠습니다.

**Comment by wannte** [comment]
```java
@Transactional
    public void updatePassword(Long userId, UpdatePasswordRequest passwordRequest) {
        User user = findUserById(userId);
        if (!encryptor.isMatch(passwordRequest.getOriginPassword(), user.getPassword())) {
            throw new CustomException("기존 패쓰워드가 일치하지 않습니다.");
        }
        user.setPassword(encryptor.hashPassword(passwordRequest.getNewPassword()));
    }
```

패쓰워드 수정 요청에 대해서, 세션에 정보가 있더라도 기존 패쓰워드를 요청받도록 구성. (로그인이 되었더라도, 다른 사용자가 몰래 비밀번호 수정을 진행할 수 있기 때문)

**Comment by wannte** [comment]
### `@PutMapping("/users/{userId}/userRole")` 관련 부분

```
public static UserRole ignoringCaseValueOf(String name) {
        try {
            return valueOf(name.toUpperCase(Locale.ROOT));
        } catch (IllegalArgumentException e) {
            throw new CustomException("존재하지 않는 유저 권한입니다.");
        }
    }
```

userRole Request에 admin, Admin, ADMIN 처럼 다양한 형식의 요청이 들어오더라도 모두 적용되야 한다고 생각.
에러 핸들링을 진행하는데 있어서 Custom Spring validation을 도입할 수도 있겠으나 우선은 코드 단에서 에러를 잡고 CutomException으로 보내주는 것으로 처리. 이후에 구현할 때, 다음 자료를 참고하면 좋을듯. [Enum Validation 참고 자료](https://www.baeldung.com/javax-validations-enums)

**Comment by wannte** [comment]
`deleteUserOfMine` 메소드에 경우 별도의 검증 값을 같이 받으면 좋겠다고 생각했고, `updatePasswordOfMine`과 같이 패쓰워드를 요구하도록 구현 -> 이 두 부분 모두 임의로 정했기 때문에, 자유롭게 의견 주셔도 좋습니다.

**Comment by koseyeon** [comment]
```
@GetMapping("/users/{userId}")
    public ResponseEntity<User> retrieveUser(@PathVariable Long userId) {
```
지금 어드민이 회원을 조회,수정,삭제 할때 userId를 파라미터로 받아오는데 이것보다 username을 받는것으로 바꾸면 어떨까요?
만약 관리자 페이지에 나중에 회원 조회,수정,삭제, 기능이 구현된다고 했을때,
userId를 입력해서 R,U,D 를 진행할 회원을 찾는 것보다 email값인 username을 입력해서 회원을 찾는게 더 나을 것 같다고 생각합니다
